### ISSUE TITLE
TLSSocketChannel BufferOverflow

### ISSUE THREAD

**Issue by vitorsvieira** [neo4j/neo4j-java-driver#177] opened 2016-05-20 15:14 UTC
Hi guys,

I'm getting the following error after running a process for 40-60 min that writes 5-8 nodes per second.

> Failed to enlarge network buffer from 16921 to 16921. This is either because the new size is however less than the old size, or because the application buffer size 8192 is so big that the application data still cannot fit into the new network buffer.

Neo4j: 3.0.0 Enterprise Trial
Driver: 1.0.0
Language: Scala 2.11.8
OS: Centos 7

And adding to that, I found a "TODO" comment in the OFFICIAL driver where this error is being traced.

[https://github.com/neo4j/neo4j-java-driver/blob/fa2986177a0b3a1cde52b1c3bfcc683d20123509/driver/src/main/java/org/neo4j/driver/internal/connector/socket/TLSSocketChannel.java#L292](https://github.com/neo4j/neo4j-java-driver/blob/fa2986177a0b3a1cde52b1c3bfcc683d20123509/driver/src/main/java/org/neo4j/driver/internal/connector/socket/TLSSocketChannel.java#L292)

``` java
 case BUFFER_OVERFLOW:
            // Enlarge the buffer and return the old status
            int curNetSize = cipherOut.capacity();
            int netSize = sslEngine.getSession().getPacketBufferSize();
            if ( curNetSize >= netSize || buffer.capacity() > netSize )
            {
                // TODO
                throw new ClientException(
                        String.format( "Failed to enlarge network buffer from %s to %s. This is either because the " +
                                       "new size is however less than the old size, or because the application " +
                                       "buffer size %s is so big that the application data still cannot fit into the " +
                                       "new network buffer.", curNetSize, netSize, buffer.capacity() ) );
            }
```

**Comment by zhenlineo** [comment] 2016-05-20 15:23
Thanks for this input. 

Would it be possible for you to recreate the error in a unit test? Or could you give us more info to help us recreate the error? We did a lot of tests around this buffer but we have not seen this error before.

We would also let you know if we get any result while investigating this error. Thanks again for the feedback.

**Comment by RodrigoLimasss** [comment] 2016-06-23 17:20
Hi guys, any date to solve this bug? 

I had the same problem.

Thanks.

**Comment by pontusmelke** [comment] 2016-06-23 20:40
@RodrigoLimasss We haven't been able to reproduce it, do you have any details about when you see this?

Regards,
Pontus

**Comment by alcarwk** [comment] 2016-09-06 04:00
Hi Guys,

It looks like we are also having this problem. Is it being worked on?

Regards,
Alan

**Comment by pontusmelke** [comment] 2016-09-06 08:05
Yes we are looking into it, we will get back to you as soon as possible,

Regards,
Pontus

**Comment by pontusmelke** [comment] 2016-09-06 13:03
By the way if you could provide us with more information it would be awesome, OS, jvm-version, how you run the queries and what type of queries would be helpful! @alcarwk

**Comment by zhenlineo** [comment] 2017-01-03 09:05
Hi,

It seems there is no more new issue report after the fix we merged on Sep 8 2016. So I am closing this issue now. Pls be free to re-open it if you still have the same problem with the latest drivers (pls specify the driver version when you report problem).

Cheers,
Zhen

**Closed as completed by zhenlineo** 2017-01-03 09:05 UTC
Labels: bug

**Comment by psnmissaka** [comment] 2017-01-16 13:42
Hi,
I got the error on driver version 1.0.3. This is the second time i came across this problem. Once in a graphenedb hosted database and another in server hosted on Digital Ocean.

**Comment by lutovich** [comment] 2017-01-16 13:48
Hi @psnmissaka,

What exact version of the driver are you using? Fix was first released in 1.1.0-M02. Could you please try latest stable 1.1.0?

**Comment by psnmissaka** [comment] 2017-01-16 14:46
Thanks @lutovich, i'm trying 1.1.0 and the error seems to have gone away.

**Comment by mixpix3ls** [comment] 2017-03-15 20:19
@lutovich  We continue to see this issue running v1.1.2:

`org.neo4j.driver.v1.exceptions.ClientException: Failed to enlarge network buffer from 16921 to 16921. This is either because the new size is however less than the old size, or because the application buffer size 8192 is so big that the application data still cannot fit into the new network buffer.`

We are using the neo4j driver in a Scala v2.11 app with Neo4j Enterprise Edition v3.0.4. Please let me know what more information I can provide.
