### ISSUE TITLE
Getting a time out exception and cannot connect to my server anymore

### ISSUE THREAD

**Issue by mburak** [neo4j/neo4j-java-driver#267] opened 2016-10-28 13:34 UTC
Hi guys, I'm getting this exception:

```
2016-10-27 03:00:11,082 [brinqa-scheduler_Worker-2]     ERROR   ExceptionPrinterJobListener:213 Exception occurred in job: Grails Job
org.quartz.JobExecutionException: org.neo4j.driver.v1.exceptions.ClientException: Unable to send messages to server: Connection timed out [See nested exception: org.neo4j.driver.v1.exceptions.ClientException: Unable to send messages to server: Connection timed out]
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

I'm running my application on a different box than my Neo4j server.
After this happens I cannot connect to the Neo4j server anymore until I restart my application. It looks like the connection gets lost for some reason and it cannot be reestablished.
This happens many times a day.

**Comment by zhenlineo** [comment] 2016-10-28 15:23
Hi may I ask which version of the Neo4j server and driver you are using?

This error seems coming from an `IOException` which happens when the driver trying to send something to the server, however the server did not repose tcp connection in time. So in another words, it seems that a basic `socketChannel.write` failed on your machine.  Do you have any load balancer in the middle between server and client?

**Comment by mburak** [comment] 2016-10-28 15:53
Hi, there's not load balancer in between client and server.
Driver version is 1.0.5 and Neo4j server version is 3.1.0-BETA1

**Comment by zhenlineo** [comment] 2016-11-23 10:45
Hi,

Sorry, we cannot reproduce this `Unable to send messages to server: Connection timed out` error.
Do you have some example code or project or any useful info that you think that would help to re-produce the error?

**Comment by technige** [comment] 2017-01-23 11:03
Closing due to lack of information.

**Closed as completed by technige** 2017-01-23 11:03 UTC
