### ISSUE TITLE
query timeout when connection pool after long time idle

### ISSUE THREAD

**Issue by newgpp** [neo4j/neo4j-java-driver#450] opened 2017-12-19 03:23 UTC
1. my bolt driver version and config
```
<dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>1.4.4</version>
</dependency>

public Driver createDriver(){
        Config config = Config.build().withConnectionTimeout(connectionTimeoutSeconds, TimeUnit.SECONDS)
                .withConnectionLivenessCheckTimeout(10L, TimeUnit.SECONDS)
                .toConfig();
        return GraphDatabase.driver(uri, AuthTokens.basic(username, password), config);
    }
```

2.my use example
```
private StatementResult queryResult(String cypherCode, Map<String, Object> params) {
        String cypher = featureConfig.getMappedCypherCode().get(cypherCode);
        try (Session session = driver.session()) {

            return session.run(cypher, params);
        }
    }
```
3.problem
I have already add `idleTimeBeforeConnectionTest` config, value is 10 seconds.
When the program long time idle, there will be timeout exception

**Comment by lutovich** [comment] 2017-12-19 08:55
Hi @newgpp,

We need a bit more information in order to help with this problem.

Please share the stacktrace you get and how often does it occur?

How does your Neo4j setup look like? Do you use single instance or a causal cluster? Do you have database in a cloud?

**Comment by lutovich** [comment] 2018-01-09 10:05
Hi @newgpp,

Do you still experience this issue?

**Comment by mariol3** [comment] 2018-01-09 14:33
Hi @lutovich ,

don't know if it's related but we experienced a similar problem on one of our applications.
We are running on a Google Cloud Infrastructure and after some time we found that this error was logged:

```
org.neo4j.driver.v1.exceptions.ClientException: Unable to process request: Connection reset by peer buffer:                                                                                                                                                                                                                                                                        
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.readNextPacket(BufferingChunkedInput.java:429) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                            
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.readChunkSize(BufferingChunkedInput.java:344) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                             
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.read(BufferingChunkedInput.java:246) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                      
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.fillScratchBuffer(BufferingChunkedInput.java:215) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                         
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.readByte(BufferingChunkedInput.java:109) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                  
        at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:441) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                           
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:405) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                              
        at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                  
        at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                  
        at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:129) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                          
        at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:108) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                
        at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:136) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                             
        at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:157) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                            
        at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:117) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]                                                                                                    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]                                                                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]                                                                          
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]                                                                                                               
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                         
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                 
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) [spring-webmvc-4.3.4.RELEASE.jar!/:
4.3.4.RELEASE]                                                                                                                                                                            
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.4.RELEASE.jar!
/:4.3.4.RELEASE]                                                                                                                                                                          
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3
.4.RELEASE]                                                                                                                                                                               
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]         
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                      
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                   
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                           
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                                             
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                          
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                                             
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.6.jar!/:8.5.6]                                                              
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE] 
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]       
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]            
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.R
ELEASE]                                                                                                                                                                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169) [spring-security-web-4.1.3.RELEA
SE.jar!/:4.1.3.RELEASE]                                                                                                                                                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]        
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]                    
       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]                
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RE
LEASE]                                                                                                                                                                                    
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-4.1.3.R
ELEASE.jar!/:4.1.3.RELEASE]                                                                                                                                                               
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]               
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]                          
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]                                  
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                             
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                   
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                              
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                      
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                          
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                       
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]                                     
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                        
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                      
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                      
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                   
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                            
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                             
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                         
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                              
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                               
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                         
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                  
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                      
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                          
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]                                                                                 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]                                                                                 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.6.jar!/:8.5.6]                                                       
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]                                                                                                                           
Caused by: java.io.IOException: Connection reset by peer                                                                                                                                  
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_111]                                                                                                             
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_111]                                                                                                     
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_111]                                                                                                        
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_111]                                                                                                                        
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_111]                                                                                                  
        at org.neo4j.driver.internal.connector.socket.TLSSocketChannel.unwrap(TLSSocketChannel.java:177) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                              
        at org.neo4j.driver.internal.connector.socket.TLSSocketChannel.read(TLSSocketChannel.java:374) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                                                
        at org.neo4j.driver.internal.connector.socket.BufferingChunkedInput.readNextPacket(BufferingChunkedInput.java:408) ~[neo4j-jdbc-driver-3.0.1.jar!/:na]                            
        ... 108 common frames omitted                                                                                                                                                                                                                                                                                                                                        ```

**Comment by lutovich** [comment] 2018-01-09 15:41
Hi @mariol3,

I do not know if it's related because we have no stacktrace from the original issue. Do you have something in the database logs around the same timestamp?

`Connection reset by peer` means connection was closed by the other side. It could be that database was shutdown, cloud infra killed the connection or transient network failure occurred.
Shutdown should be visible in the database logs. Idle TCP connection timeout can most likely be configured for cloud machines or load balancer (quick googling points to this page https://cloud.google.com/compute/docs/troubleshooting section "Communicating between your instances and the Internet").

So you might want to tweak `MaxConnectionLifetime` (more details [here](http://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management)) available from 1.5.0 or/and `ConnectionLivenessCheckTimeout` via `Config#withConnectionLivenessCheckTimeout(long, TimeUnit)` available from 1.1.1.

Hope this helps!

P.S. I changed formatting of the stacktrace in your message a bit. Hope that's ok by you :)

**Comment by lutovich** [comment] 2018-02-09 16:33
Closing because of inactivity. Please feel free to post more if problem still exists.

**Closed as completed by lutovich** 2018-02-09 16:33 UTC

**Comment by haris-zynka** [comment] 2019-11-25 12:47
Have to ask this again. When using latest OGM it defaults to 4.0 bolt driver which I guess is not in stable version. However I can see this was long time ago and issue.

Whatever tweaking I do with the withConnectionTimeout & withConnectionLivenessCheckTimeout & withMaxConnectionPoolSize & withConnectionAcquisitionTimeout it still drops exception after being idle for too long. Problem is that locally it works for 30 sec before dropping exception and finally reconnecting. On Azure I couldn't wait enough to see how long does it take. 

These are latest tests:
```java
.withConnectionAcquisitionTimeout(1, TimeUnit.SECONDS)
                .withConnectionTimeout(1, TimeUnit.SECONDS)
                .withConnectionLivenessCheckTimeout(500, TimeUnit.MILLISECONDS)
                .withMaxConnectionPoolSize(3)
                .withMaxTransactionRetryTime(2, TimeUnit.SECONDS)
```

UPDATE: I retested it with settings and now it takes ~ 19 seconds so it's not always 30 locally but it varies from 19 to 32. Exception message
```
Nov 25, 2019 1:47:00 PM org.neo4j.driver.internal.logging.JULogger warn
WARNING: [0x9a293542][94.245.90.10:7687][bolt-730] Fatal error occurred in the pipeline
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by zhenlineo** [comment] 2019-11-25 12:55
Hi @haris-zynka,

I cannot see how your issue is related to the query timeout issue in this old thread. I would suggest  you to open a new issue following our issue template with formal description of your problem again.

Please state clearly what you are trying to achieve and how the behaviour is different from what you've expected.

Cheers,
Zhen

**Comment by LakshmiRadhakrishnan09** [comment] 2020-02-04 06:55
Hi,
I am facing a very similar issue with org.neo4j.driver 4.0.0. Connection attempts after/around 1 hr of idle time takes too long to respond.

If we are making calls to Neo4j server through our java spring boot application after an idle time of 1 hr, the neo4j calls are taking significant time to finish.

Steps to Reproduce:

Do many read/write operation in neo4j using spring boot application
Wait for 55 minutes( do not perform any read/write operation. Make the system idle)
Try doing read/write operation in neo4j using spring boot application
Operations completes after 15 mits
We are not seeing this issue, if idle time is more than 1hr.

As seen in the logs below thread with id 0xc55afaab, is trying to acquire a connection from pool at 14.19GMT, but the attempt is failed after 15 minutes(14:35 GMT).

Neo4j Server: neo4j 4.0.0(stand alone)

Spring Boot:
neo4j-java-driver-spring-boot-starter : 4.0.0
org.neo4j.driver:4.0.0

Logs from spring boot driver:

2020-02-03T14:19:01.768315 FINEST ConnectionPool - Acquiring a connection from pool towards 10.8.173.183:80
2020-02-03T14:19:01.768461 FINEST NettyChannelHealthChecker - Channel [id: 0xc55afaab, L:/10.29.17.80:38998 - R:/10.8.173.183:80] has been idle for 3555901 and needs a ping
2020-02-03T14:19:01.768543 FINE OutboundMessageHandler - [0xc55afaab][10.8.173.183:80][bolt-295] C: RESET
2020-02-03T14:19:01.768616 FINEST OutboundMessageHandler - [0xc55afaab][10.8.173.183:80][bolt-295] C: 0002b00f

2020-02-03T14:35:27.707388 WARNING ChannelErrorHandler - [0xc55afaab][10.8.173.183:80][bolt-295] Fatal error occurred in the pipeline
2020-02-03T14:35:27.707503 FINEST NettyChannelHealthChecker - Channel [id: 0xc55afaab, L:/10.29.17.80:38998 - R:/10.8.173.183:80] failed ping org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database failed
2020-02-03T14:35:27.70771 FINE ChannelErrorHandler - [0xc55afaab][10.8.173.183:80][bolt-295] Closing channel because of a failure 'java.io.IOException: Operation timed out'
2020-02-03T14:35:27.707807 FINE ChannelErrorHandler - [0xc55afaab][10.8.173.183:80][bolt-295] Channel is inactive.

2020-02-03T14:35:27.707811 FINE OutboundMessageHandler - [0x6f5d81bc][10.8.173.183:80][bolt-788] C: RESET
2020-02-03T14:35:27.707899 FINEST OutboundMessageHandler - [0x6f5d81bc][10.8.173.183:80][bolt-788] C: 0002b00f
2020-02-03T14:35:27.751055 FINEST ChunkDecoder - [0x6f5d81bc][10.8.173.183:80][bolt-788] S: 0003b170a0
2020-02-03T14:35:27.751175 FINEST ChunkDecoder - [0x6f5d81bc][10.8.173.183:80][bolt-788] S: 0000
2020-02-03T14:35:27.751235 FINEST InboundMessageHandler - [0x6f5d81bc][10.8.173.183:80][bolt-788] S: b170a0
2020-02-03T14:35:27.751268 FINE InboundMessageDispatcher - [0x6f5d81bc][10.8.173.183:80][bolt-788] S: SUCCESS {}

idleTimeBeforeConnectionTest is set to 0, so that very connection will be tested before attempt. 
Soon after this failure another thread is acquired successfully and query was executed.

**Comment by haris-zynka** [comment] 2020-02-04 08:35
@LakshmiRadhakrishnan09 please verify if #653  can help. My problem was with the Max Connnection Lifetime in Azure.

**Comment by vishnuprakash-thoughtworks-sde** [comment] 2022-04-19 09:03
> #653

hi @LakshmiRadhakrishnan09 ,
We are also facing a similar issue. Were you able to fix it. If yes, what was the fix. Any input will be appreciated.
Regards,
Vishnu
