### ISSUE TITLE
Exception in thread "main" org.neo4j.driver.v1.exceptions.ClientException: The client is unauthorized due to authentication failure.

### ISSUE THREAD

**Issue by chenrui11** [neo4j/neo4j-java-driver#271] opened 2016-11-08 02:48 UTC

**Comment by zhenlineo** [comment] 2016-11-08 09:01
Hi,

Is this error happens on the start of a driver session? Or it happens in the middle of running a statement? 
If it happens at the start of `driver.session()`. then I think it probably because you are using a wrong password? or you are using the default password neo4j? Remember that you need to change your default password before you use the driver.

Cheers,
Zhen

**Comment by chenrui11** [comment] 2016-11-08 11:39
Use "neo4j-shell" to change the password ,but  find the AuthorizationViolationException.
neo4j-sh (?)$ CALL dbms.changePassword("admin");
AuthorizationViolationException: Invalid attempt to change the password

**Comment by zhenlineo** [comment] 2016-11-08 12:06
How about direct go to the browser on port 7474 to change the password? Is that work for you?

**Comment by chenrui11** [comment] 2016-11-08 12:22
I konw ,but I can`t  go to the  linux server use  browser...

**Comment by zhenlineo** [comment] 2016-11-09 13:52
Hi I failed to reproduce your problem. Could you give us more information of what server + client version that you are using and other related info that you think it might be useful to re-produce your problem?

**Comment by zhenlineo** [comment] 2016-11-14 14:55
Hi, I got your problem. You were trying to change the password via shell in 3.0. The shell does not support it yet in 3.0.

If it is for 3.0, do something like this:

```
driver = GraphDatabase.driver("bolt://localhost", auth=basic_auth("neo4j", "neo4j"))
session = driver.session()
session.run("call dbms.changePassword('a new password')")
session.close()
driver.close() *
```

Then you are ready to go with a new driver with new password ever after.

`*The code is python`

Cheers,
Zhen

**Comment by zhenlineo** [comment] 2016-11-23 09:05
Hi I am closing this issue as we've confirm an solution to it. Pls be free to re-open if you still get any problem to change the default password.

**Closed as completed by zhenlineo** 2016-11-23 09:05 UTC

**Comment by yogpurohit** [comment] 2018-03-08 22:29
Hi,
I am having the same issue while connecting to neo4j
driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic( "neo4j", "neo4j"));
I am not sure how to change default passwd as suggested above.  Appreciate any help..
