### ISSUE TITLE
Failed to enlarge network buffer still occurring in 1.1.2

### ISSUE THREAD

**Issue by mixpix3ls** [neo4j/neo4j-java-driver#335] opened 2017-03-16 04:11 UTC
We continue to see Issue #177 running v1.1.2:

org.neo4j.driver.v1.exceptions.ClientException: Failed to enlarge network buffer from 16921 to 16921. This is either because the new size is however less than the old size, or because the application buffer size 8192 is so big that the application data still cannot fit into the new network buffer.

We are using the neo4j driver in a Scala v2.11 app with Neo4j Enterprise Edition v3.0.4.

Please let me know what more information I can provide to help troubleshoot or diagnose this issue.

**Comment by technige** [comment] 2017-07-17 08:40
Should be fixed by https://github.com/neo4j/neo4j-java-driver/pull/390

**Comment by lutovich** [comment] 2017-07-21 08:50
Hi @mixpix3ls,

We expect https://github.com/neo4j/neo4j-java-driver/pull/389 to fix this problem. It has beed merged and released in version 1.4.2. Could you please try it and let us know if the problem is gone?

Thanks.

**Closed as completed by lutovich** 2017-07-21 08:50 UTC
