### ISSUE TITLE
Bolt drive performance - REST doing better

### ISSUE THREAD

**Issue by vishwajitmankar** [neo4j/neo4j-java-driver#459] opened 2018-01-16 12:08 UTC
This is in continuation of my previous issue #443 . Wanted to post further observation which might help you. I was not sure where else I can post my observations. 
I ran my test program on Linux 4 core, 32 GB RAM server. I set Page cache to 10GB and Heap to 12 and 16 GB. The request were sent from a different Linux server. 
As data grew, REST performance was better than BOLT driver. MATCH query performance for both REST and BOLT was same. Test program which I ran had same cypher query for both REST as well BOLT. Please let me know if you have any suggestions to improve performance. For now, we have decided to continue using REST instead of Bolt.

```
String query = "UNWIND $props AS properties " +
	               "CREATE (n:PERFORMANCE:REST:NODE1) " +
	               "SET n = properties";

String query = "UNWIND $props AS properties " +
	               "MATCH (n:PERFORMANCE:REST { uuid: properties.uuid}) " +
	               "SET n.isUpdated = true, n.updaterValue = properties.updaterValue";
```

For REST I used Jersey client - com.sun.jersey.api.client.WebResource 
```
WebResource resource = Client.create().resource("http://neo4jURL:7474/db/data/transaction/commit");
		ClientResponse response = resource.accept( MediaType.APPLICATION_JSON ).header("Authorization", "xxxxxxxxxxx")
				.type(MediaType.APPLICATION_JSON)
				.entity(requestJson.toString())
				.post(ClientResponse.class);
```

Driver connection pool was used with 25 max connections and code was simple -
session.writeTransaction( tx -> tx.run( query, gitParameters ) );

There was sleep time (2 sec, 3 sec, 10 mins etc) in between CREATE and UPDATE executions. 
Please check below output -- 

Using Bolt started ... Fri Jan 12 12:51:00 UTC 2018
Total currnt DB Records --202000
Bolt Total records created -- 1000
Bolt record creation time -- 1200
BOLT UPDATE query execution time for Records 500 is - 123

Using REST started ... Fri Jan 12 13:23:09 UTC 2018
Total currnt DB Records --203000
REST Total nodes created -- 1000
REST nodes creation time -- 1200
REST UPdate query execution time for nodes - 500 is - 80

Total currnt DB Records --260000
Bolt Total records created -- 20000
Bolt record creation time -- 121
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 175
BOLT UPDATE query execution time for Records 500 is - 178
BOLT UPDATE query execution time for Records 500 is - 178
BOLT UPDATE query execution time for Records 500 is - 178
BOLT UPDATE query execution time for Records 500 is - 174

Using REST started ... Mon Jan 15 05:59:10 UTC 2018
Total currnt DB Records --280000
REST Total nodes created -- 20000
REST nodes creation time -- 123
REST UPdate query execution time for nodes - 500 is - 126
REST UPdate query execution time for nodes - 500 is - 127
REST UPdate query execution time for nodes - 500 is - 126
REST UPdate query execution time for nodes - 500 is - 126
REST UPdate query execution time for nodes - 500 is - 127
REST UPdate query execution time for nodes - 500 is - 126
....

Please let me know if I can send entire code for review.

**Comment by lutovich** [comment] 2018-01-17 13:05
Hi @vishwajitmankar,

It would be very valuable to see your code and have a reliable repro. Du you think it's possible for you to create a test database of structure similar to your production database? We could then run same Jersey client an this driver against it.

Please feel free to attach or create gist with entire code. It'd be valuable to see how results from Jersey and driver are consumed.

**Comment by vishwajitmankar** [comment] 2018-01-22 05:02
Sorry for late reply. I was out of office. Below is gist link - 
https://gist.github.com/vishwajitmankar/b45d47947cb4f98518ca7d1f82b1fa10

I have put all related code too. I am not consuming output yet, Does that make any difference? I think it's App server responsibility and performance has been better there.  Idea was to test performance of Neo4j DB with 2 different protocol. This test program is according to my business requirement. 
I ran it as standalone program on a different server connecting to Neo4j which is separate server with server config mentioned in my first query. 
I had new DB with zero nodes. My program creates as many records as you need in a batch of 500 with sleep time in between. It also updates the records in batch of 500. You can also specify whether you want to delete nodes at the end of the test. Current test program can further be extended to create offline relationship between nodes too (which is how our business requirement is). I will do that later.

Note - Some of the code can be optimized and generalize further, however, please ignore it for now :)

Please let me know if you need further information in this regard.

**Comment by lutovich** [comment] 2018-01-23 10:09
Thanks for attaching the code @vishwajitmankar. We will investigate.

**Comment by lutovich** [comment] 2018-02-02 18:57
Hi @vishwajitmankar,

I tried your code and can't reproduce the slowness. Bolt seems to be faster than REST:

```
Total currnt DB Records --0
Bolt Total records created -- 200000
Bolt record creation time -- 51697ms
BOLT MATCH query execution time - 142ms
BOLT UPDATE query execution time for Records 500 is - 79030ms
BOLT MATCH query execution time - 27ms
BOLT UPDATE query execution time for Records 500 is - 79696ms
BOLT MATCH query execution time - 18ms
BOLT UPDATE query execution time for Records 500 is - 80237ms
BOLT MATCH query execution time - 14ms
BOLT UPDATE query execution time for Records 500 is - 82466ms
BOLT MATCH query execution time - 13ms
BOLT UPDATE query execution time for Records 500 is - 85123ms
BOLT MATCH query execution time - 13ms
BOLT UPDATE query execution time for Records 500 is - 82654ms
BOLT MATCH query execution time - 12ms
BOLT UPDATE query execution time for Records 500 is - 84404ms
BOLT MATCH query execution time - 11ms
BOLT UPDATE query execution time for Records 500 is - 82454ms
BOLT MATCH query execution time - 11ms
BOLT UPDATE query execution time for Records 500 is - 81659ms
BOLT MATCH query execution time - 11ms
BOLT UPDATE query execution time for Records 500 is - 85030ms
Bolt Total records updated -- 5000
Bolt record update time -- 824099ms
Bolt record deletion time -- 7151ms
Using Bolt ended ... Fri Feb 02 19:03:46 CET 2018

Sleeping for 5 seconds before starting REST code...
Using REST started ... Fri Feb 02 19:03:51 CET 2018
Total currnt DB Records --0
REST Total nodes created -- 200000
REST nodes creation time -- 57953ms
REST MATCH query execution time - 130ms
REST UPdate query execution time for nodes - 500 is - 104827ms
REST MATCH query execution time - 54ms
REST UPdate query execution time for nodes - 500 is - 106095ms
REST MATCH query execution time - 37ms
REST UPdate query execution time for nodes - 500 is - 106348ms
REST MATCH query execution time - 32ms
REST UPdate query execution time for nodes - 500 is - 106195ms
REST MATCH query execution time - 30ms
REST UPdate query execution time for nodes - 500 is - 107114ms
REST MATCH query execution time - 32ms
REST UPdate query execution time for nodes - 500 is - 106117ms
REST MATCH query execution time - 31ms
REST UPdate query execution time for nodes - 500 is - 105907ms
REST MATCH query execution time - 31ms
REST UPdate query execution time for nodes - 500 is - 105645ms
REST MATCH query execution time - 31ms
REST UPdate query execution time for nodes - 500 is - 105948ms
REST MATCH query execution time - 35ms
REST UPdate query execution time for nodes - 500 is - 106918ms
REST Total nodes updated -- 5000
REST nodes update time -- 1062630ms
REST nodes deletion time -- 4147ms
Using REST ended ... Fri Feb 02 19:22:36 CET 2018
```

Also noticed that update queries are slightly different for Bolt and REST. Bolt:
```
UNWIND $props AS properties
MATCH (n:PERFORMANCE { uuid: properties.uuid})
SET n.isUpdated = true, n.updaterValue = properties.updaterValue
```

REST:
```
UNWIND $props AS properties
MATCH (n:PERFORMANCE:REST { uuid: properties.uuid})
SET n.isUpdated = true, n.updaterValue = properties.updaterValue
```

So Bolt query has to potentially return and process more nodes. Please change `n:PERFORMANCE` to `n:PERFORMANCE:BOLT` to verify if it's the case.

**Comment by vishwajitmankar** [comment] 2018-02-05 07:05
Did you run the program after changing the query or ran it as is and still observing better performance with BOLT? 
I am using Neo4j v3.3.0 community version, if I have not mentioned that before.

Thank you for pointing out the query difference. That should make the difference. I will run the program again and check performance difference.

**Comment by lutovich** [comment] 2018-02-06 09:27
I executed code with original query and saw Bolt performing a bit better than REST. Used neo4j community 3.3.1.

**Comment by vishwajitmankar** [comment] 2018-02-06 09:36
Unfortunately I am not observing any improvement so far on my local server. REST and BOLT are either equal REST better. Any suggestions? What might be going wrong on server?
I will be running the test on new Linux servers with 32GB RAM and 100 GB HDD. Let's see how it behaves.

**Comment by lutovich** [comment] 2018-02-06 09:59
There might be another thing to tweak. Bolt driver runs with encryption turned on by default. However, jersey client in the code uses unencrypted connection. You could try to turn encryption on in the REST client as well. Otherwise bolt connections have to do more work.

**Comment by vishwajitmankar** [comment] 2018-02-14 07:19
I re-ran the program on fresh DB with brand new AWS env and by correcting the query, however, I still don't see much improvement in my environment.  

Slpeeing for 5 seconds... to start new execution
Using Bolt started ... Tue Feb 06 21:43:26 UTC 2018
Total currnt DB Records --182000
Bolt Total records created -- 10000
Bolt record creation time -- 13
Match query - MATCH (n:PERFORMANCE:BOLT) where not exists(n.isUpdated) return n LIMIT 500
Update query - UNWIND $props AS properties MATCH (n:PERFORMANCE:BOLT { uuid: properties.uuid}) SET n.isUpdated = true, n.updaterValue = properties.updaterValue
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 317
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 308
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 311
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 315
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 295
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 321
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 318

Using Bolt ended ... Tue Feb 06 23:31:15 UTC 2018
Sleeping for 5 seconds before starting REST code...
Using REST started ... Tue Feb 06 23:31:20 UTC 2018
Total currnt DB Records --192000
REST Total nodes created -- 10000
REST nodes creation time -- 18
Match query - MATCH (n:PERFORMANCE:REST) where not exists(n.isUpdated) return n LIMIT 500
Update query - UNWIND $props AS properties MATCH (n:PERFORMANCE:REST { uuid: properties.uuid}) SET n.isUpdated = true, n.updaterValue = properties.updaterValue
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 328
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 342
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 334
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 325
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 333
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 329

**Comment by lutovich** [comment] 2018-02-20 10:18
@vishwajitmankar did you try using HTTPS instead of HTTP or turning encryption off in the bolt driver?

**Comment by vishwajitmankar** [comment] 2018-02-23 06:06
I tried with disabling encryption, without much performance improvement -
dbms.connector.bolt.enabled=true
dbms.connector.bolt.tls_level=DISABLED
dbms.connector.bolt.listen_address=:7687

Regards...

**Comment by lutovich** [comment] 2018-04-24 13:27
Hi @vishwajitmankar,

I tried to reproduce the described behavior using two AWS m4.xlarge machines but failed. In my setup one machine hosts a neo4j database (3.4.0-rc1) and other hosts the client application (with java driver 1.5.2). This application has pretty much the same code as in your earlier gist. I only changed `defaultRecords` to be 10000 in `TestExecuteNeo4jPerformance` and made code use configured hostname instead of `localhost`. Here is the output:

```
Total currnt DB Records --140000
Bolt Total records created -- 20000
Bolt record creation time -- 21
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
BOLT MATCH query execution time - 0
BOLT UPDATE query execution time for Records 500 is - 14
Bolt Total records updated -- 10500
Bolt record update time -- 320
Using Bolt ended ... Tue Apr 24 13:12:26 UTC 2018

Sleeping for 5 seconds before starting REST code...

Using REST started ... Tue Apr 24 13:12:31 UTC 2018
Total currnt DB Records --160000
REST Total nodes created -- 20000
REST nodes creation time -- 22
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 21
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 20
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 21
REST MATCH query execution time - 0
REST UPdate query execution time for nodes - 500 is - 21
REST Total nodes updated -- 10500
REST nodes update time -- 450
Using REST ended ... Tue Apr 24 13:20:24 UTC 2018
```

Timings are in seconds and REST calls seem to be consistently slower.

I'll close this issue because there seem to be no good way for us to reproduce the described behaviour. Please feel free to update this issue if you think I've missed something or there is a different way to reproduce the same problem.

**Closed as completed by lutovich** 2018-04-24 13:27 UTC
